# Generated by Django 3.2.3 on 2021-11-01 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_places_parking', models.CharField(max_length=200)),
                ('input_date', models.TimeField(default=datetime.datetime.now)),
                ('parking_day_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
