# Generated by Django 3.2.3 on 2021-11-01 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='free_places_parking',
            field=models.CharField(help_text='How many free space you saw', max_length=200),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_day_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Please pick up the date'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
