# Generated by Django 3.2.3 on 2021-11-01 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='user',
        ),
        migrations.AddField(
            model_name='parking',
            name='user_name',
            field=models.CharField(default='cwayacita', editable=False, help_text='Your user', max_length=200),
        ),
        migrations.AlterField(
            model_name='parking',
            name='free_places_parking',
            field=models.CharField(help_text='How many parking available you have seen', max_length=200),
        ),
        migrations.AlterField(
            model_name='parking',
            name='input_date',
            field=models.TimeField(default=datetime.datetime(2021, 11, 1, 11, 16, 11, 65218), editable=False, help_text='Date Event'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_day_date',
            field=models.DateTimeField(default='01/11/2021', help_text='Please pick up the date'),
        ),
    ]
