# Generated by Django 3.2.3 on 2021-11-01 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20211101_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparking',
            name='input_date',
            field=models.TimeField(default=datetime.datetime(2021, 11, 1, 11, 38, 52, 752770), editable=False, help_text='Date Event'),
        ),
    ]
