# Generated by Django 3.2.3 on 2021-11-01 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_modelparking_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparking',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 11, 57, 40, 101555), editable=False, help_text='Date Event'),
        ),
        migrations.AlterField(
            model_name='modelparking',
            name='parking_day_date',
            field=models.DateField(default='01/11/2021', help_text='Please pick up the date'),
        ),
    ]
