# Generated by Django 3.2.3 on 2021-11-01 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20211101_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparking',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 11, 59, 53, 417299), editable=False, help_text='Date Event'),
        ),
    ]
