# Generated by Django 3.2.3 on 2021-11-01 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_alter_modelparking_input_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelparking',
            options={'ordering': ('-input_date',)},
        ),
        migrations.AlterField(
            model_name='modelparking',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 12, 56, 29, 852755), editable=False, help_text='Date Event'),
        ),
    ]
