# Generated by Django 3.2.3 on 2021-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_alter_modelparking_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparking',
            name='input_date',
            field=models.DateTimeField(default='2021-11-01 13:04', editable=False, help_text='Date Event'),
        ),
    ]
